---
title: "Google map review analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load libraries

```{r}
library(tidyverse)
library(ggplot2)
library(showtext)
showtext_auto()
```

## Review Tfidf graph

```{r}
review_tfidf <- readRDS("../Rdata/reviews_tfidf.rds")

# calculate the tfidf for a specific place and ratings
tfidf_filter <- function (place, ratings) {
  filtered <- review_tfidf %>%
    filter(place_id == !!place, rating %in% !!ratings) %>%
    group_by(word) %>%
    select(word, tf_idf) %>%
    summarize(tf_idf = sum(tf_idf)) %>%
    arrange(desc(tf_idf)) %>%
    ungroup() %>%
    slice_max(tf_idf, n = 15)
  return(filtered)
}

res <- tfidf_filter("ChIJHYeewoupQjQRo1LvtfKwHYY", c(4, 5))
res %>%
  ggplot(aes(x = tf_idf, y = fct_reorder(word, tf_idf))) +
  geom_col()
```

## Rating Tfidf graph

```{r}
library(tidytext)

stopword <- read.delim("../data/stopword.txt")

reviews_df <- readRDS("../Rdata/reviews_jeiba.rds")

review_tidy <- reviews_df %>%
  unnest_tokens(
    output = "word",
    input = "text",
    token = "regex",
    pattern = "\u3000"
  )

review_filter_stopword <- review_tidy %>%
  filter(! word %in% stopword$X)

review_without_stopword <- review_filter_stopword %>%
  count(rating, word) %>%
  bind_tf_idf(word, rating, n) %>%
  arrange(desc(n))

# plot by frequency
review_without_stopword %>%
  group_by(rating) %>%
  slice_max(n, n = 10) %>%
  ungroup() %>%
  ggplot(aes(n, fct_reorder(word, n, sum), fill = rating)) +
  geom_col(show.legend = TRUE) +
  labs(x = "Frequency", y = NULL)

```

## Type rating

```{r}
place_df <- readRDS("../Rdata/places.rds")

place_df_separated <- place_df %>%
  filter(!is.na(rating)) %>%
  separate_rows(types, sep = ",", convert = TRUE)

# plot the rating distribution of every types of places
place_types_rating <- place_df_separated %>%
  group_by(types) %>%
  summarize(n = n(),
            avg = mean(rating),
            std = sd(rating)) %>%
  filter(n > 10) %>%
  arrange(desc(n))

place_df_separated %>%
  filter(types %in% place_types_rating$types) %>%
  ggplot(aes(x=fct_reorder(as.factor(types), rating), y=rating)) +
  geom_boxplot() +
  labs(x = "Place Type") +
  coord_flip()
```

## 不同類型地標的評論重點詞

```{r}
types <- c("health", "food", "gym", "book_store")
place_ids <- lapply(types, function (x) {
  ret <- place_df_separated %>% filter(types == x)
  ret <- ret$id
  return(ret)
})
for (i in seq_along(place_ids)) {
  print(
    temp <- review_filter_stopword %>%
      filter(place_id %in% place_ids[[i]]) %>%
      count(rating, word) %>%
      arrange(desc(n)) %>%
      group_by(rating) %>%
      slice_max(n, n = 10) %>%
      ungroup() %>%
      ggplot(aes(n, fct_reorder(word, n, sum), fill = rating)) +
      geom_col(show.legend = TRUE) +
      labs(title = types[[i]], x = "Frequency", y = NULL)
  )
}
```

## 評分高低的評論重點詞差異

```{r}
for (i in 1:5) {
  print(
    review_without_stopword %>%
      group_by(rating) %>%
      slice_max(n, n = 15) %>%
      ungroup() %>%
      filter(rating == i) %>%
      ggplot(aes(n, fct_reorder(word, n, sum), fill = rating)) +
      geom_col(show.legend = FALSE) +
      labs(title = paste0("Rating = ", as.character(i)), x = "Frequency", y = NULL)
  )
}
```

```{r}
# USAGE:
#   input a word you want to analyze and will print out the positive/negative/total
#   comments, and the slice_max returns the most apparent performance of num places

reviews_with_name <- readRDS("../Rdata/review_jieba_with_name.rds")

words_filter <- function(word = '燈光', tag = 'pos', num = 25) {
  filtered <- reviews_with_name %>%
    filter(grepl(word, text)) %>%
    group_by(name) %>%
    summarise(pos = sum(rating %in% c(4,5)), neg = sum(rating %in% c(1,3)))
  
  if (tag == 'pos') {
    filtered <- filtered %>% 
      slice_max(pos, n = num)
  } else if (tag == 'neg') {
     filtered <- filtered %>% 
      slice_max(neg, n = num)
  } else if (tag == 'total') {
     filtered <- filtered %>% 
      slice_max(pos+neg, n = num)
  }
  
  return(filtered)
}

res <- words_filter(word = '衛生', tag = 'pos', num = 25)

# the y should be two tags, I will fix this when showing in the web page
res %>%
  ggplot(aes(x = name, y = pos)) +
  geom_col() +
  coord_flip()

```
